import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      colors: {
        "border-subtle": "#1E293B",
        "surface-tint": "#ffb95f",
        "on-tertiary-fixed-variant": "#004c69",
        "tertiary-fixed": "#c4e7ff",
        "surface-container": "#1c2028",
        "on-surface": "#dfe2ee",
        "surface-dim": "#0f131c",
        "state-warning": "#F59E0B",
        "tertiary-container": "#38bdf8",
        "secondary-fixed": "#6ffbbe",
        "surface-card": "#131B2E",
        "on-tertiary-fixed": "#001e2c",
        "on-primary-container": "#613b00",
        "on-secondary-container": "#00311f",
        "outline-variant": "#534434",
        "error-container": "#93000a",
        "text-muted": "#64748B",
        "surface-variant": "#31353e",
        "text-primary": "#F8FAFC",
        "surface-container-high": "#262a33",
        "mining-gold-bright": "#FBBF24",
        "surface-container-highest": "#31353e",
        "surface-container-lowest": "#0a0e16",
        "mining-gold-deep": "#D97706",
        "on-primary-fixed": "#2a1700",
        "primary-container": "#f59e0b",
        "on-secondary-fixed": "#002113",
        "state-critical": "#EF4444",
        surface: "#0f131c",
        outline: "#a08e7a",
        secondary: "#4edea3",
        background: "#0f131c",
        "surface-container-low": "#181c24",
        "inverse-primary": "#855300",
        "surface-bright": "#353942",
        error: "#ffb4ab",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#653e00",
        "on-primary": "#472a00",
        "surface-hover": "#1E293B",
        "border-crisp": "#24324D",
        "on-surface-variant": "#d8c3ad",
        "text-secondary": "#94A3B8",
        "on-secondary-fixed-variant": "#005236",
        "secondary-container": "#00a572",
        "tertiary-fixed-dim": "#7bd0ff",
        "secondary-fixed-dim": "#4edea3",
        "on-error-container": "#ffdad6",
        "govtech-emerald-dim": "#064E3B",
        "govtech-emerald": "#10B981",
        primary: "#ffc174",
        "on-secondary": "#003824",
        "on-tertiary": "#00354a",
        "on-tertiary-container": "#004965",
        "primary-fixed-dim": "#ffb95f",
        "surface-base": "#0B0F17",
        "inverse-surface": "#dfe2ee",
        "primary-fixed": "#ffddb8",
        "on-background": "#dfe2ee",
        "inverse-on-surface": "#2c3039",
        tertiary: "#8ed5ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "workspace-width-ratio": "68%",
        "space-xs": "0.25rem",
        "space-2xs": "0.125rem",
        "space-sm": "0.5rem",
        "space-3xl": "3rem",
        "space-md": "0.75rem",
        "sidebar-width-ratio": "32%",
        "space-base": "1rem",
        "space-lg": "1.25rem",
        "space-xl": "1.5rem",
        gutter: "1rem",
        "space-2xl": "2rem",
      },
      fontFamily: {
        "headline-md": ["var(--font-inter)"],
        "body-md": ["var(--font-inter)"],
        "body-lg": ["var(--font-inter)"],
        "mono-metric-md": ["var(--font-jetbrains)"],
        "body-sm": ["var(--font-inter)"],
        "mono-metric-lg": ["var(--font-jetbrains)"],
        "mono-label": ["var(--font-jetbrains)"],
        "mono-citation": ["var(--font-jetbrains)"],
        "headline-xl": ["var(--font-inter)"],
        "headline-lg": ["var(--font-inter)"],
        "headline-xl-mobile": ["var(--font-inter)"],
      },
      fontSize: {
        "headline-md": [
          "20px",
          { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" },
        ],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "mono-metric-md": [
          "18px",
          { lineHeight: "24px", fontWeight: "600" },
        ],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "mono-metric-lg": [
          "28px",
          { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "mono-label": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" },
        ],
        "mono-citation": [
          "11px",
          { lineHeight: "14px", fontWeight: "500" },
        ],
        "headline-xl": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "700" },
        ],
        "headline-lg": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "headline-xl-mobile": [
          "28px",
          { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
